


icp_odometry:
  icp_objective: PointToPlane
  max_correspondence_dist: 0.25
  knn_normal_estimation: 4
  max_n_iter: 25
  downsampling_ratio: 0.4
  crop_box_min_x: -25.0
  crop_box_min_y: -25.0
  crop_box_min_z: -100.0
  crop_box_max_x: 25.0
  crop_box_max_y: 25.0
  crop_box_max_z: 100.0
  
icp_mapping:
  map_voxel_size: 0.05
  min_movement_between_mapping_steps: 0.2
  min_refinement_fitness: 0.7
  scan_to_map_refinement:
    icp_objective: PointToPlane
    max_correspondence_dist: 3.0
    knn_normal_estimation: 5
    max_n_iter: 50
    downsampling_ratio: 0.4
    crop_box_min_x: -30.0
    crop_box_min_y: -30.0
    crop_box_min_z: -100.0
    crop_box_max_x: 30.0
    crop_box_max_y: 30.0
    crop_box_max_z: 100.0
  map_builder:
    crop_box_min_x: -100.0
    crop_box_min_y: -100.0
    crop_box_min_z: -100.0
    crop_box_max_x: 100.0
    crop_box_max_y: 100.0
    crop_box_max_z: 100.0    