


icp_odometry:
  icp_objective: PointToPlane
  max_correspondence_dist: 0.5
  knn_normal_estimation: 4
  voxel_filter_size: 0.15
  max_n_iter: 25
  downsampling_ratio: 0.5
  crop_box_min_x: -35.0
  crop_box_min_y: -35.0
  crop_box_min_z: -100.0
  crop_box_max_x: 35.0
  crop_box_max_y: 35.0
  crop_box_max_z: 100.0
  
icp_mapping:
  map_voxel_size: 0.2
  min_movement_between_mapping_steps: 0.2
  min_refinement_fitness: 0.7
  scan_to_map_refinement:
    icp_objective: PointToPlane
    max_correspondence_dist: 3.0
    knn_normal_estimation: 5
    max_n_iter: 50
    voxel_filter_size: 0.2
    downsampling_ratio: 0.5
    crop_box_min_x: -40.0
    crop_box_min_y: -40.0
    crop_box_min_z: -100.0
    crop_box_max_x: 40.0
    crop_box_max_y: 40.0
    crop_box_max_z: 100.0
  map_builder:
    dense_map_downsampling_ratio: 1.0
    crop_box_min_x: -50.0
    crop_box_min_y: -50.0
    crop_box_min_z: -100.0
    crop_box_max_x: 50.0
    crop_box_max_y: 50.0
    crop_box_max_z: 100.0
    
local_map:
  downsampling_ratio: 0.25
  crop_box_min_x: -20.0
  crop_box_min_y: -20.0
  crop_box_min_z: -100.0
  crop_box_max_x: 20.0
  crop_box_max_y: 20.0
  crop_box_max_z: 100.0

    